tabs to spaces

diff --git a/cert_status b/cert_status
--- a/cert_status
+++ b/cert_status
@@ -86,7 +86,7 @@ EOF
 
 
 function usageExamples() {
-	usage
+  usage
 cat << EOF
 
 Example - Show status of a single certificate in test environment:
@@ -148,29 +148,29 @@ EOF
 
 
 function showVersion() {
-	echo ${VERSION}
+  echo ${VERSION}
 }
 
 
 function log() {
-	if [[ ! -z ${VERBOSE} ]]; then
-		echo "LOG: $*" 1>&2;
-	fi
+  if [[ ! -z ${VERBOSE} ]]; then
+    echo "LOG: $*" 1>&2;
+  fi
 }
 
 
 function lwarn() {
-	echo "WARN: $*" 1>&2;
+  echo "WARN: $*" 1>&2;
 }
 
 
 function lerror() {
-	echo "ERROR: $*" 1>&2;
+  echo "ERROR: $*" 1>&2;
 }
 
 
 function dumpCertificate() {
-	openssl x509 -noout -text -in ${CERTIFICATE}
+  openssl x509 -noout -text -in ${CERTIFICATE}
 }
 
 
@@ -221,118 +221,118 @@ reversea() {
 
 
 function getCertificateInfo() {
-	local _TMP=$(openssl x509 -subject -noout -in ${CERTIFICATE})
-	old_IFS=$IFS
-	IFS=$'/' _TMP=(${_TMP#*/})
-	IFS=${old_IFS}
-	_TMP=$(printf ",%s" "${_TMP[@]}")
-	#echo ${_TMP}
+  local _TMP=$(openssl x509 -subject -noout -in ${CERTIFICATE})
+  old_IFS=$IFS
+  IFS=$'/' _TMP=(${_TMP#*/})
+  IFS=${old_IFS}
+  _TMP=$(printf ",%s" "${_TMP[@]}")
+  #echo ${_TMP}
   reversea _TMP _TMP2
   #echo "${_TMP[@]}"
   #echo "${_TMP2[@]}\n"
   #echo "==="
   #eval eval echo "'\"\${_TMP['{$((${#_TMP[@]}-1))..0}']}\"'"
   #echo
-	c_DN=${_TMP:1}
-	c_DN=$(echo ${c_DN//[[:blank:]]/} | tr -d \")
+  c_DN=${_TMP:1}
+  c_DN=$(echo ${c_DN//[[:blank:]]/} | tr -d \")
   splitBy "," ${c_DN};
   #_TMP
-	_TMP=$(openssl x509 -enddate -noout -in ${CERTIFICATE} \
-		        | awk -F= ' /notAfter/ { printf("%s\n",$NF); } ');
-	c_expire_date=$(toSerialDate "${_TMP}")
-	_TMP=$(openssl x509 -startdate -noout -in ${CERTIFICATE} \
-		        | awk -F= ' /notBefore/ { printf("%s\n",$NF); } ');
-	c_create_date=$(toSerialDate "${_TMP}")
-	_TMP=$(openssl x509 -serial -noout -in ${CERTIFICATE})
-	c_serial=${_TMP##*=}
-	cDaysToExpire=$(echo "(${c_expire_date}-${TNOW})/(60*60*24)" |bc);
-	_TMP=""
-	if [[ -z ${CACHAINFILE} ]]; then
-	  	if [[ -f ${CAROOTCERT} ]]; then
-			if [[ -f ${CACERT} ]]; then
+  _TMP=$(openssl x509 -enddate -noout -in ${CERTIFICATE} \
+            | awk -F= ' /notAfter/ { printf("%s\n",$NF); } ');
+  c_expire_date=$(toSerialDate "${_TMP}")
+  _TMP=$(openssl x509 -startdate -noout -in ${CERTIFICATE} \
+            | awk -F= ' /notBefore/ { printf("%s\n",$NF); } ');
+  c_create_date=$(toSerialDate "${_TMP}")
+  _TMP=$(openssl x509 -serial -noout -in ${CERTIFICATE})
+  c_serial=${_TMP##*=}
+  cDaysToExpire=$(echo "(${c_expire_date}-${TNOW})/(60*60*24)" |bc);
+  _TMP=""
+  if [[ -z ${CACHAINFILE} ]]; then
+      if [[ -f ${CAROOTCERT} ]]; then
+      if [[ -f ${CACERT} ]]; then
         cat ${CAROOTCERT} > ${TMPFILE}
         cat ${CACERT} >> ${TMPFILE}
         CACHAINFILE=${TMPFILE}
-			else
-				log "CACERT file not found: ${CACERT}"
-			fi
-		else
-			log "CAROOTCERT file not found: ${CAROOTCERT}"
-		fi
-	fi
-	if [[ -f ${CACHAINFILE} ]]; then
-		c_revoked="Not_Revoked"
-		c_valid="Valid"
-		log "CACHAINFILE = ${CACHAINFILE}"
-		old_IFS=$IFS
-		IFS=$'\n' _TMP=($(openssl verify -CAfile ${CACHAINFILE} ${CERTIFICATE}))
-		IFS=${old_IFS}
-		for sslError in "${_TMP[@]}"; do
-			if [[ $sslError == 'error'* ]]; then
-				lwarn $sslError
-				if [[ $sslError == 'error 23'* ]]; then
-					c_revoked="Revoked"
-				fi
-				if [[ $sslError == 'error 20'* ]]; then
-					c_valid="Invalid"
-				fi
-			fi
-		done
-	else
-		log "CACHAINFILE file not found: ${CACHAINFILE}"
-	fi
-	if [[ ! -z ${getAuthor} ]]; then
-		c_author=$(${SVN} blame --xml ${CERTIFICATE} | ${XML} sel -t -m "//entry[1]/commit" -v "author" -n)
-	fi
+      else
+        log "CACERT file not found: ${CACERT}"
+      fi
+    else
+      log "CAROOTCERT file not found: ${CAROOTCERT}"
+    fi
+  fi
+  if [[ -f ${CACHAINFILE} ]]; then
+    c_revoked="Not_Revoked"
+    c_valid="Valid"
+    log "CACHAINFILE = ${CACHAINFILE}"
+    old_IFS=$IFS
+    IFS=$'\n' _TMP=($(openssl verify -CAfile ${CACHAINFILE} ${CERTIFICATE}))
+    IFS=${old_IFS}
+    for sslError in "${_TMP[@]}"; do
+      if [[ $sslError == 'error'* ]]; then
+        lwarn $sslError
+        if [[ $sslError == 'error 23'* ]]; then
+          c_revoked="Revoked"
+        fi
+        if [[ $sslError == 'error 20'* ]]; then
+          c_valid="Invalid"
+        fi
+      fi
+    done
+  else
+    log "CACHAINFILE file not found: ${CACHAINFILE}"
+  fi
+  if [[ ! -z ${getAuthor} ]]; then
+    c_author=$(${SVN} blame --xml ${CERTIFICATE} | ${XML} sel -t -m "//entry[1]/commit" -v "author" -n)
+  fi
 }
 
 
 function showCertificateInfo() {
-	local cdate=$(fromSerialDate ${c_create_date})
-	local edate=$(fromSerialDate ${c_expire_date})
-	if [[ ${OUTFORMAT} == "CSV" ]]; then
-		echo -e "\"${CERTIFICATE}\"${DLMT}${c_serial}${DLMT}\"${c_DN}\"${DLMT}${c_revoked}${DLMT}${c_valid}${DLMT}${cDaysToExpire}${DLMT}${edate}${DLMT}${cdate}"
-	elif [[ ${OUTFORMAT} == "JSON" ]]; then
-		echo "{"
-		echo " \"File_name\"   : \"${CERTIFICATE}\","
-		echo " \"Author\"      : \"${c_author}\","
-		echo " \"Serial\"      : \"${c_serial}\","
-		echo " \"DN\"          : \"${c_DN}\","
-		echo " \"Created\"     : \"${cdate}\","
-		echo " \"Expires\"     : \"${edate}\","
-		echo " \"Expires_days\": ${cDaysToExpire},"
-		echo " \"Revocation\"  : \"${c_revoked}\","
-		echo " \"Validity\"    : \"${c_valid}\""
-		echo "}"
-	else
-		echo "Certificate : $(basename ${CERTIFICATE})"
-		echo "Author      : ${c_author}"
-		echo "Serial      : ${c_serial}"
-		echo "DN          : ${c_DN}"
-		echo "Created     : ${cdate}"
-		echo "Expires     : ${edate}"
-		echo "Expires_days: ${cDaysToExpire}"
-		echo "Revocation  : ${c_revoked}"
-		echo "Validity    : ${c_valid}"
-	fi
+  local cdate=$(fromSerialDate ${c_create_date})
+  local edate=$(fromSerialDate ${c_expire_date})
+  if [[ ${OUTFORMAT} == "CSV" ]]; then
+    echo -e "\"${CERTIFICATE}\"${DLMT}${c_serial}${DLMT}\"${c_DN}\"${DLMT}${c_revoked}${DLMT}${c_valid}${DLMT}${cDaysToExpire}${DLMT}${edate}${DLMT}${cdate}"
+  elif [[ ${OUTFORMAT} == "JSON" ]]; then
+    echo "{"
+    echo " \"File_name\"   : \"${CERTIFICATE}\","
+    echo " \"Author\"      : \"${c_author}\","
+    echo " \"Serial\"      : \"${c_serial}\","
+    echo " \"DN\"          : \"${c_DN}\","
+    echo " \"Created\"     : \"${cdate}\","
+    echo " \"Expires\"     : \"${edate}\","
+    echo " \"Expires_days\": ${cDaysToExpire},"
+    echo " \"Revocation\"  : \"${c_revoked}\","
+    echo " \"Validity\"    : \"${c_valid}\""
+    echo "}"
+  else
+    echo "Certificate : $(basename ${CERTIFICATE})"
+    echo "Author      : ${c_author}"
+    echo "Serial      : ${c_serial}"
+    echo "DN          : ${c_DN}"
+    echo "Created     : ${cdate}"
+    echo "Expires     : ${edate}"
+    echo "Expires_days: ${cDaysToExpire}"
+    echo "Revocation  : ${c_revoked}"
+    echo "Validity    : ${c_valid}"
+  fi
 }
 
 
 function showHeader() {
-	if [[  ${OUTFORMAT} == "JSON" ]]; then
-		echo "{\"what\":\"Certificate Status\","
-		echo " \"Generated\":\"$(date +${dateformat_out})\","
-		echo " \"content\":["
-	else
-		echo -e "File${DLMT}Serial${DLMT}DN${DLMT}Revoked${DLMT}Validity${DLMT}Expire_days${DLMT}Expires${DLMT}Created"
-	fi
+  if [[  ${OUTFORMAT} == "JSON" ]]; then
+    echo "{\"what\":\"Certificate Status\","
+    echo " \"Generated\":\"$(date +${dateformat_out})\","
+    echo " \"content\":["
+  else
+    echo -e "File${DLMT}Serial${DLMT}DN${DLMT}Revoked${DLMT}Validity${DLMT}Expire_days${DLMT}Expires${DLMT}Created"
+  fi
 }
 
 
 function showFooter() {
-	if [[ ${OUTFORMAT} == "JSON" ]]; then
-		echo "]}"
-	fi
+  if [[ ${OUTFORMAT} == "JSON" ]]; then
+    echo "]}"
+  fi
 }
 
 # Create an event for a .ics file
@@ -350,11 +350,11 @@ EOF
 
 
 function generateEventCalendar() {
-	# Create calendar with events:
-	# - Certificate revocation update date
-	# - Expiration dates for certificates
-	local c_file="${APPDIR}/${CERT_ENVIRONMENT}_events.ics"
-	log "Generating calendar file ${c_file}"
+  # Create calendar with events:
+  # - Certificate revocation update date
+  # - Expiration dates for certificates
+  local c_file="${APPDIR}/${CERT_ENVIRONMENT}_events.ics"
+  log "Generating calendar file ${c_file}"
     printf "BEGIN:VCALENDAR\n" > ${c_file}
     printf "VERSION:2.0\n" >> ${c_file}
     printf "PRODID:-//DataONE.org//${APPNAME} v${VERSION}//${CERT_ENVIRONMENT}//EN\n" >> ${c_file}
@@ -362,19 +362,19 @@ function generateEventCalendar() {
     #Each certificate
     CERTIFICATES=$(find -L "${CERT_FOLDER}/certs" -name "*.pem")
     for CERTIFICATE in ${CERTIFICATES}; do
-    	#get certificate info and generate event
-    	getCertificateInfo
-    	if [[ ${c_revoked} == "Not_Revoked" ]]; then
-    		log "${c_DN} expires $(fromSerialDate ${c_expire_date})"
+      #get certificate info and generate event
+      getCertificateInfo
+      if [[ ${c_revoked} == "Not_Revoked" ]]; then
+        log "${c_DN} expires $(fromSerialDate ${c_expire_date})"
       # Extract CN from the normalized DN string. If CN isn't present, fall back to the full DN.
       c_CN=$(printf '%s' "${c_DN}" | sed -n 's/.*CN=\([^,]*\).*/\1/p')
       if [[ -z "${c_CN}" ]]; then
         c_CN="${c_DN}"
       fi
-			ICAL_EVENT=$(serialDateToVCalendar \
-			  "${c_expire_date}" "${CERT_ENVIRONMENT} Cert ${c_CN} expires")
-			printf "${ICAL_EVENT}\n" >> ${c_file}
-		fi
+      ICAL_EVENT=$(serialDateToVCalendar \
+        "${c_expire_date}" "${CERT_ENVIRONMENT} Cert ${c_CN} expires")
+      printf "${ICAL_EVENT}\n" >> ${c_file}
+    fi
     done
 
     #Close calendar
@@ -385,74 +385,74 @@ function generateEventCalendar() {
 #=== Main ===
 while getopts "hHvdVsnSAPL:a:c:C:e:" OPTION
 do
-	case ${OPTION} in
-		h) usage; exit 1;;
-		H) usageExamples; exit 1;;
-		v) showVersion; exit 1;;
-		d) DUMPCERT=1;;
-		V) VERBOSE=1;;
-		a) CACERT=$OPTARG;;
-		c) CAROOTCERT=$OPTARG;;
-		C) CACHAINFILE=$OPTARG;;
-		s) OUTFORMAT="CSV";;
-		n) OUTFORMAT="HUMAN";;
-		S) showHeader; exit 1;;
-		A) getAuthor=1;;
+  case ${OPTION} in
+    h) usage; exit 1;;
+    H) usageExamples; exit 1;;
+    v) showVersion; exit 1;;
+    d) DUMPCERT=1;;
+    V) VERBOSE=1;;
+    a) CACERT=$OPTARG;;
+    c) CAROOTCERT=$OPTARG;;
+    C) CACHAINFILE=$OPTARG;;
+    s) OUTFORMAT="CSV";;
+    n) OUTFORMAT="HUMAN";;
+    S) showHeader; exit 1;;
+    A) getAuthor=1;;
     e) expire_within=$OPTARG;;
-		P) CERT_ENVIRONMENT="Prod";
-		   CERT_FOLDER="${PROD_INT_FOLDER}";
-		   CAROOTCERT="${PROD_CAROOTCERT}";
-		   CACERT="${PROD_CACERT}";;
-		L) GENERATE_CALENDAR=1;;
-		\?) usage; exit 1;;
-	esac
+    P) CERT_ENVIRONMENT="Prod";
+       CERT_FOLDER="${PROD_INT_FOLDER}";
+       CAROOTCERT="${PROD_CAROOTCERT}";
+       CACERT="${PROD_CACERT}";;
+    L) GENERATE_CALENDAR=1;;
+    \?) usage; exit 1;;
+  esac
 done
 
 shift $(($OPTIND - 1))
 if [[ -z ${1} ]]; then
-	lwarn "Certificate file name or folder is required"
-	lwarn "Defaulting to the ${CERT_ENVIRONMENT} environment."
-	TARGET="${CERT_FOLDER}/certs"
+  lwarn "Certificate file name or folder is required"
+  lwarn "Defaulting to the ${CERT_ENVIRONMENT} environment."
+  TARGET="${CERT_FOLDER}/certs"
 else
-	TARGET=${1}
+  TARGET=${1}
 fi
 if [[ ! -z ${GENERATE_CALENDAR} ]]; then
-	generateEventCalendar
-	exit 0;
+  generateEventCalendar
+  exit 0;
 fi
 if [[ -f ${TARGET} ]]; then
-	# Report on single certificate
-	CERTIFICATE=${TARGET}
-	log "Certificate file: ${CERTIFICATE}"
-	if [[ ! -z ${DUMPCERT} ]]; then
-		dumpcertificate
-		exit 0;
-	fi
-	getCertificateInfo
-	showCertificateInfo
-	exit 0;
+  # Report on single certificate
+  CERTIFICATE=${TARGET}
+  log "Certificate file: ${CERTIFICATE}"
+  if [[ ! -z ${DUMPCERT} ]]; then
+    dumpcertificate
+    exit 0;
+  fi
+  getCertificateInfo
+  showCertificateInfo
+  exit 0;
 else
-	if [[ -d ${TARGET} ]]; then
-		# Report on *.pem in folder
-		_starter=""
-		showHeader
-		CERTIFICATES=$(find -L ${TARGET} -name "*.pem")
-		for CERTIFICATE in ${CERTIFICATES}; do
-			log "Certificate file: ${CERTIFICATE}"
-			getCertificateInfo
+  if [[ -d ${TARGET} ]]; then
+    # Report on *.pem in folder
+    _starter=""
+    showHeader
+    CERTIFICATES=$(find -L ${TARGET} -name "*.pem")
+    for CERTIFICATE in ${CERTIFICATES}; do
+      log "Certificate file: ${CERTIFICATE}"
+      getCertificateInfo
       if [[ "${cDaysToExpire}" < "${expire_within}" ]] && [[ "${cDaysToExpire}" > "-${expire_within}" ]]; then
         if [[ -n ${_starter} ]]; then
           if [[ ${OUTFORMAT} == "JSON" ]]; then
             echo ","
           fi
         fi
-  			showCertificateInfo
+        showCertificateInfo
       fi
-			_starter="1"
-		done
-		showFooter
-	else
-		lerror "Supplied target is not a file or folder"
-		exit 1;
-	fi
+      _starter="1"
+    done
+    showFooter
+  else
+    lerror "Supplied target is not a file or folder"
+    exit 1;
+  fi
 fi
