Fixed revocation checking, added examples and environment convenience switch

diff --git a/cert_status b/cert_status
--- a/cert_status
+++ b/cert_status
@@ -2,17 +2,65 @@
 
 #Given name of a certificate, report on:
 # DN
+# Serial
 # Date created
 # Date of expiration
 # Days to expiration
 # Revocation status
+#
+# Example:
+# Show status of a single certificate in test environment:
+#  
+#   ./cert_status -A DataONETestIntCA/certs/urn\:node\:mnTestGulfWatch.pem  
+#
+#
+# Example:
+# Show status of a single certificate in production environment, explicitly
+# indicating which certificates and CRL to use:
+#
+#   ./cert_status -A -P DataONEProdCA/certs/urn\:node\:GULFWATCH.pem
+# 
+#    
+# Example:
+# Show status of a single certificate in production environment, explicitly
+# indicating which certificates and CRL to use:
+#
+#   ./cert_status -A -r DataONEProdCA/crl/DataONEProdCA_CRL.pem \
+#    -a DataONEProdCA/certs/DataONEProdCA.pem \
+#    -c DataONERootCA/certs/DataONERootCA.pem \
+#    DataONEProdCA/certs/urn\:node\:GULFWATCH.pem
+#
+#
+# Example: 
+# Generate a pipe delimited text file reporting on all 
+# the test certificates:
+#
+#   ./cert_status -H > testcerts.csv; \
+#   for f in $(find DataONETestIntCA/certs -name *.pem); \
+#   do ./cert_status -A -s $f >> testcerts.csv; done
+#
+#
+# Example: 
+# Generated a pipe delimited text file reporting on all
+# the production certificates:
+#
+#   ./cert_status -H > testcerts.csv; \
+#   for f in $(find DataONETestIntCA/certs -name *.pem); \
+#   do ./cert_status -A -s \
+#    -r DataONEProdCA/crl/DataONEProdCA_CRL.pem \
+#    -a DataONEProdCA/certs/DataONEProdCA.pem \
+#    -c DataONERootCA/certs/DataONERootCA.pem \
+#   $f >> prodcerts.csv; done
+#  
 
-VERSION="1.0.1"
+
+VERSION="1.0.2"
+INSTALLDIR=$(dirname ${0})
 VERBOSE=""
 CERTIFICATE=""
-CAROOTCERT="DataONETestCA/certs/DataONETestCA.pem"
-CACERT="DataONETestIntCA/certs/DataONETestIntCA.pem"
-CRL="DataONETestIntCA/crl/DataONETestInt_CRL.pem"
+CAROOTCERT="${INSTALLDIR}/DataONETestCA/certs/DataONETestCA.pem"
+CACERT="${INSTALLDIR}/DataONETestIntCA/certs/DataONETestIntCA.pem"
+CRL="${INSTALLDIR}/DataONETestIntCA/crl/DataONETestInt_CRL.pem"
 CACHAINFILE=""
 cDN=""
 cCreateDate=""
@@ -22,6 +70,7 @@ cSerial=""
 cAuthor=""
 dumpCert=""
 CSVOUTPUT=""
+getAuthor=""
 
 XML=xml
 SVN=svn
@@ -32,6 +81,7 @@ TNOW=$(date -u +%s)
 
 function usage() {
 cat << EOF
+$(basename $0) version ${VERSION}
 
 usage: $(basename $0) OPTIONS Certificate 
 
@@ -48,8 +98,8 @@ OPTIONS:
   -c  The CAROOTCERT.pem file (${CAROOTCERT})
   -C  CA Chain file, containing CACERT, CAROOT, and CRL
   -H  Generate CSV header and exit
-
-echo "$(basename $0) version ${VERSION}"
+  -A  Lookup author from subversion (default: No)
+  -P  Use default production environment certs instead of test
 
 Checking revocation requires that the cacert.pem and the crl.pem
 are available.
@@ -67,6 +117,11 @@ function log() {
 	if [[ ! -z ${VERBOSE} ]]; then
 		echo "LOG: $@" 1>&2;
 	fi
+}
+
+
+function lerror() {
+	echo "ERROR: $@" 1>&2;
 }
 
 
@@ -131,18 +186,23 @@ function getCertificateInfo() {
 		fi
 	fi
 	if [[ -f ${CACHAINFILE} ]]; then
+		cRevoked="Not_Revoked"
 		log "CACHAINFILE = ${CACHAINFILE}"
-		_TMP=$(openssl verify -CAfile ${CACHAINFILE} ${CERTIFICATE})
-		cRevoked=$(echo ${_TMP##*\:} | sed -e 's/^[[:space:]]*//')
-		if [[ $cRevoked == "OK" ]]; then
-			cRevoked="Not_Revoked"
-		else
-			cRevoked="Revoked"
-		fi
+		IFS=$'\n' _TMP=($(openssl verify -crl_check -CAfile ${CACHAINFILE} ${CERTIFICATE}))
+		for sslError in "${_TMP[@]}"; do
+			if [[ $sslError == 'error'* ]]; then
+				lerror $sslError
+				if [[ $sslError == 'error 23'* ]]; then
+					cRevoked="Revoked"
+				fi
+			fi
+		done
 	else
 		log "CACHAINFILE file not found: ${CACHAINFILE}"
 	fi
-	cAuthor=$(${SVN} blame --xml ${CERTIFICATE} | ${XML} sel -t -m "//entry[1]/commit" -v "author" -n)
+	if [[ ! -z ${getAuthor} ]]; then
+		cAuthor=$(${SVN} blame --xml ${CERTIFICATE} | ${XML} sel -t -m "//entry[1]/commit" -v "author" -n)
+	fi
 }
 
 
@@ -152,7 +212,7 @@ function showCertificateInfo() {
 	fromSerialDate ${cExpireDate}
 	local edate=${RES}
 	if [[ ${CSVOUTPUT} == "1" ]]; then
-		echo "${CERTIFICATE}|${cDN}|${cRevoked}|${cDaysToExpire}|${edate}|${cdate}|${cAuthor}"
+		echo "${CERTIFICATE}|${cSerial}|${cDN}|${cRevoked}|${cDaysToExpire}|${edate}|${cdate}|${cAuthor}"
 	else
 		echo "----"
 		echo "File_name: \"${CERTIFICATE}\""
@@ -171,12 +231,12 @@ function showHeader() {
 	echo "#Certificate Status"
 	echo "#Generated|$(date ${dateformat_out})"
 	echo "#"
-	echo "File|DN|Revoked|Expire_days|Expires|Created|Author"
+	echo "File|Serial|DN|Revoked|Expire_days|Expires|Created|Author"
 }
 
 
 #=== Main ===
-while getopts "hvVdsHr:a:c:C:" OPTION
+while getopts "hvVdsHAPr:a:c:C:" OPTION
 do
 	case ${OPTION} in
 		h) usage; exit 1;;
@@ -189,6 +249,10 @@ do
 		C) CACHAINFILE=$OPTARG;;
 		s) CSVOUTPUT=1;;
 		H) showHeader; exit 1;;
+		A) getAuthor=1;;
+		P) CAROOTCERT="${INSTALLDIR}/DataONERootCA/certs/DataONERootCA.pem";
+		   CACERT="${INSTALLDIR}/DataONEProdCA/certs/DataONEProdCA.pem";
+		   CRL="${INSTALLDIR}/DataONEProdCA/crl/DataONEProdCA_CRL.pem";;
 		\?) usage; exit 1;;
 	esac
 done
