Create Node Cert (PEM & PK) only, locally

diff --git a/publish_cert_orcid b/publish_cert_orcid
--- a/publish_cert_orcid
+++ b/publish_cert_orcid
@@ -5,40 +5,21 @@
 #
 
 VERSION="1.0.0"
-APPNAME=$(basename ${0})
-APPDIR=$(pwd)
+APPNAME="$(basename ${0})"
+APPDIR="$(pwd)"
 TMPDIR="/tmp"
 
 PUBLISH_HOST="project.dataone.org"
 PUBLISH_PATH="/var/www/project/html/o"
-
-PROD_INT_FOLDER="${APPDIR}/DataONEProdIntCA"
-PROD_CAROOTCERT="${APPDIR}/DataONEProdRootCA/certs/DataONEProdRootCA.pem"
-PROD_CACERT="${PROD_INT_FOLDER}/certs/DataONEProdIntCA.pem"
-PROD_CRL="${PROD_INT_FOLDER}/crl/DataONEProdIntCA_CRL.pem"
-
-TEST_INT_FOLDER="${APPDIR}/DataONETestIntCA"
-TEST_CAROOTCERT="${APPDIR}/DataONETestCA/certs/DataONETestCA.pem"
-TEST_CACERT="${TEST_INT_FOLDER}/certs/DataONETestIntCA.pem"
-TEST_CRL="${TEST_INT_FOLDER}/crl/DataONETestInt_CRL.pem"
-
-#Default to use the TEST environment
-CERT_ENVIRONMENT="Test"
-CERT_FOLDER="${TEST_INT_FOLDER}"
-CAROOTCERT=${TEST_CAROOTCERT}
-CACERT=${TEST_CACERT}
-CRL=${TEST_CRL}
 
 VERBOSE=""
 DRYRUN=""
 USER_ID=""
 CERTIFICATE=""
 
-
 function showVersion() {
     echo ${VERSION}
 }
-
 
 function usage() {
 cat << EOF
@@ -53,6 +34,7 @@ OPTIONS:
   -h  Show this message
   -H  Show this message with examples
   -D  Dry run. Show what will be done.
+  -P  Create Node Cert (PEM file with embedded Private Key) only, and do not publish to server
   -v  Show version and exit
   -V  Verbose output to STDERR
 
@@ -65,7 +47,6 @@ CERTIFICATE
 EOF
 }
 
-
 function usageExamples() {
     usage
 cat << EOF
@@ -76,23 +57,19 @@ Example - Share a certificate and key for user vieglais:
 EOF
 }
 
-
 function log() {
-    if [[ ! -z ${VERBOSE} ]]; then
-        echo "LOG: $@" 1>&2;
+    if [[ -n ${VERBOSE} ]]; then
+        echo "LOG: $*" 1>&2;
     fi
 }
 
-
 function lwarn() {
-    echo "WARN: $@" 1>&2;
+    echo "WARN: $*" 1>&2;
 }
-
 
 function lerror() {
-    echo "ERROR: $@" 1>&2;
+    echo "ERROR: $*" 1>&2;
 }
-
 
 #Check LDAP for the uid ${1}. If present, output "1", otherwise "0"
 function verifyUserId() {
@@ -139,8 +116,9 @@ function shareCertificate() {
         cp ${_KEY} "${_tmp_dir}/private/${_safename}.key"
         cp ${CERTIFICATE} "${_tmp_dir}/private/${_safename}.pem"
         cat ${_KEY} >> "${_tmp_dir}/private/${_safename}.pem"
-        cp ${_CSR} "${_tmp_dir}/${_safename}.csr"
-        cat > "${_tmp_dir}/README.txt" << EOF
+        if [[ -z $LOCAL_ONLY ]]; then
+            cp ${_CSR} "${_tmp_dir}/${_safename}.csr"
+            cat > "${_tmp_dir}/README.txt" << EOF
 README
 ======
 
@@ -187,23 +165,34 @@ Metadata About Certificate
 --------------------------
 
 EOF
-if [[ ${_certpath} == *"DataONEProdIntCA"* ]]; then
-  echo "${_certpath} is a PRODUCTION cert"
-  statusFlag="-P"
-else
-  echo "${_certpath} is a TEST cert"
-  statusFlag=""
-fi
-echo "Doing /cert_status..."
+        fi
+
+        if [[ ${_certpath} == *"DataONEProdIntCA"* ]]; then
+          echo "${_certpath} is a PRODUCTION cert"
+          statusFlag="-P"
+        else
+          echo "${_certpath} is a TEST cert"
+          statusFlag=""
+        fi
+        echo "Doing /cert_status..."
         ${APPDIR}/cert_status ${statusFlag} -n ${CERTIFICATE} >> "${_tmp_dir}/README.txt"
     fi
-echo "Creating zipfile..."
+
+    if [[ -n $LOCAL_ONLY ]]; then
+        rm "${_tmp_dir}/${_safename}.crt" "${_tmp_dir}/private/${_safename}.key" "${_tmp_dir}/README.txt"
+        echo "PEM file WITH KEY created locally (NOT uploaded to server) at:"
+        echo "${_tmp_dir}/private/${_safename}.pem"
+        echo "* * * CONFIDENTIAL! Delete when done! * * *"
+        return
+    fi
+
+    echo "Creating zipfile..."
     local _ZIPFILE="${TMPDIR}/${_safename}.zip"
     local CDIR=$(pwd)
-    cd ${TMPDIR}
+    cd ${TMPDIR} || exit
     log "zip -r ${_ZIPFILE} ${_safename}"
     if [[ -z ${DRYRUN} ]]; then
-        if [[ ! -z ${VERBOSE} ]]; then
+        if [[ -n ${VERBOSE} ]]; then
             zip -r ${_ZIPFILE} ${_safename}
         else
             zip -q -r ${_ZIPFILE} ${_safename}
@@ -211,13 +200,13 @@ echo "Creating zipfile..."
         if [ "$?" -ne "0" ]; then
             lerror "Zip creation failed."
             lwarn "Aborting."
-            cd ${CDIR}
+            cd ${CDIR} || exit
             rm -rf ${_tmp_dir}
             rm ${_ZIPFILE}
             exit 1
         fi
     fi
-    cd ${CDIR}
+    cd ${CDIR} || exit
 
     #scp the .zip, creating a folder if needed
     log "Copy to host..."
@@ -244,7 +233,7 @@ echo "Creating zipfile..."
 
 
 # === Main ===
-while getopts "hHvVD:" OPTION
+while getopts "hHvVDP" OPTION
 do
     case ${OPTION} in
         h) usage; exit 1;;
@@ -252,6 +241,7 @@ do
         v) showVersion; exit 1;;
         V) VERBOSE=1;;
         D) DRYRUN=1;;
+        P) LOCAL_ONLY=1;;
         \?) usage; exit 1;;
     esac
 done
